<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-21T15:11:19 IST" name="Failed suite [Suite]" finished-at="2024-09-21T15:11:38 IST" duration-ms="18796">
    <groups>
    </groups>
    <test started-at="2024-09-21T15:11:19 IST" name="Test(failed)" finished-at="2024-09-21T15:11:38 IST" duration-ms="18796">
      <class name="task.BrokenLinks">
        <test-method is-config="true" signature="initialise()[pri:0, instance:task.BrokenLinks@4b6e2263]" started-at="2024-09-21T15:11:19 IST" name="initialise" finished-at="2024-09-21T15:11:29 IST" duration-ms="9918" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialise -->
        <test-method signature="BrokenLinkTest()[pri:0, instance:task.BrokenLinks@4b6e2263]" started-at="2024-09-21T15:11:29 IST" name="BrokenLinkTest" finished-at="2024-09-21T15:11:34 IST" duration-ms="4600" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Link: 'Appium' is broken with status code 403 expected [true] but found [false],
Link: 'Broken Link' is broken with status code 404 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Link: 'Appium' is broken with status code 403 expected [true] but found [false],
Link: 'Broken Link' is broken with status code 404 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at task.BrokenLinks.BrokenLinkTest(BrokenLinks.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BrokenLinkTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:task.BrokenLinks@4b6e2263]" started-at="2024-09-21T15:11:34 IST" name="tearDown" finished-at="2024-09-21T15:11:34 IST" duration-ms="281" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- task.BrokenLinks -->
      <class name="practiceSelenium.LoginBaseClass">
        <test-method is-config="true" signature="launchUrl()[pri:0, instance:practiceSelenium.LoginBaseClass@525575]" started-at="2024-09-21T15:11:34 IST" name="launchUrl" finished-at="2024-09-21T15:11:38 IST" duration-ms="3664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchUrl -->
        <test-method signature="UrlValidateTest()[pri:1, instance:practiceSelenium.LoginBaseClass@525575]" started-at="2024-09-21T15:11:38 IST" name="UrlValidateTest" finished-at="2024-09-21T15:11:38 IST" duration-ms="36" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UrlValidateTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:practiceSelenium.LoginBaseClass@525575]" started-at="2024-09-21T15:11:38 IST" name="tearDown" finished-at="2024-09-21T15:11:38 IST" duration-ms="224" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- practiceSelenium.LoginBaseClass -->
    </test> <!-- Test(failed) -->
  </suite> <!-- Failed suite [Suite] -->
</testng-results>
